version: '3.8'

services:
  app:
    build: .
    container_name: temp-sensor
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://charming_swartz:8812/qdb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=quest
    networks:
      - sensor-network
networks:
  sensor-network:
    external: true
